version: '3.9'

services:
  mongo:
    container_name: "mongodb"
    image: mongo
    restart: always
    volumes:
      - ./.mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb123
      MONGO_INITDB_DATABASE: dbtest

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: dev
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
  api:
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run start"
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-express
    environment:
      PORT: 3000
    networks:
      - backend

networks:
  backend:
